### ISSUE TITLE
Support modules required for netboot.xyz

### ISSUE THREAD

**Issue by BrassyPanache** [leahneukirchen/hrmpf#18]
I've requested that hrmpf be added to [netboot.xyz](https://netboot.xyz) (see: netbootxyz/netboot.xyz#993).  If you aren't familiar; netboot.xyz provides a small image (2MB) that presents a list of distribution install images and rescue images which you may boot.  When a distribution is selected, netboot.xyz will download and boot the selected image. It's quite simple functionality - but very useful. Especially in the context of being able to boot into a rescue image if something goes wrong with your installation.

In the past there was a request upstream for a modification to the Void Live ISO (see: void-linux/void-mklive#97) required to support netboot.xyz.  This was rejected by the maintainers.  I was wondering if you'd be comfortable adding the required support in for hrmpf?  I think it would be a very useful addition to netboot.xyz.

**Comment by leahneukirchen** [comment]
I think this could be useful indeed, even if hrmpf isn't very slim for netbooting.

Do you know btw whether Hetzner Cloud supports netboot.xyz? The last time I wanted to install Void there, I ended up dumping hrmpf on disk and booting it...

**Comment by leahneukirchen** [comment]
Looking at the linked issue, it seems our dracut 053 doesn't have livenet?

**Comment by BrassyPanache** [comment]
> I think this could be useful indeed, even if hrmpf isn't very slim for netbooting.
> 
> Do you know btw whether Hetzner Cloud supports netboot.xyz? The last time I wanted to install Void there, I ended up dumping hrmpf on disk and booting it...

I use OVH myself - and I've found that the easiest method is to simply boot from the netboot.xyz [ISO](https://netboot.xyz/docs/booting/iso) by mounting it over IPMI.  As the netboot ISO is only 2 MB it is much faster than mounting a regular Linux ISO.  This approach would probably work with Hetzner as well.

In some cases I've found that the netboot.xyz ISO does not detect the network correctly.  In these cases I simply use the OVH provided rescue CD to create a EFI partition and put the netboot.xyz [EFI image](https://boot.netboot.xyz/ipxe/netboot.xyz-snp.efi) there.  I then use [efibootmgr](https://wiki.gentoo.org/wiki/Efibootmgr) to add the image as a boot option.

**Comment by leahneukirchen** [comment]
Problem is Hetzner doesn't support custom ISO :( But IIRC there was a GPXE ISO available.

Not sure what to make out of that thumbs up comment... what's the replacement for livenet?

**Comment by leahneukirchen** [comment]
Nvm, it's moved to the dracut-network package.

**Comment by leahneukirchen** [comment]
But I'm not sure what's exactly needed now. You'll extract the initrd and submit it to netboot.xyz?

**Comment by BrassyPanache** [comment]
> But I'm not sure what's exactly needed now. You'll extract the initrd and submit it to netboot.xyz?

I've just found a [page](https://netboot.xyz/docs/faq#will-my-favorite-distribution-work-with-netbootxyz) which gives some direction.  I'll try this out and get back to you.

**Comment by leahneukirchen** [comment]
I tried the memdisk approach (it seems to need 4G), but it hangs after "Loading boot sector... booting...".

**Comment by BrassyPanache** [comment]
This is a bit out of my depth - but would you be OK if I asked on netbootxyz/netboot.xyz#993 for some support?  It seems like the maintainers are quite helpful.

**Comment by leahneukirchen** [comment]
Okay, I think I got it to work.  Essentially, I add `--force-add livenet` to the dracut call, and then I can boot it in QEMU with 

```
qemu-system-x86_64 -enable-kvm -m 2048 -net nic -net user -kernel /tmp/boot/vmlinuz -initrd /tmp/boot/initrd -append "root=live:http://10.0.0.30:8080/LiveOS/squashfs.img ro rd.luks=0 rd.md=0 rd.dm=0 loglevel=6"
```

(files extracted from the iso.)
