### ISSUE TITLE
chroot helper script?

### ISSUE THREAD

**Issue by drudru** [leahneukirchen/hrmpf#19]
Hello,

Is there a shell script that will do the typical chroot process?
It would be helpful.

Here is an example:
```
mount -t proc proc /mnt/proc
mount -t sysfs sys /mnt/sys
mount -B /dev /mnt/dev
mount -t devpts pts /mnt/dev/pts
mount -t vfat /dev/sdb1 /mnt/boot/efi
chroot /mnt /bin/bash
```

Or is there an easy way to persist files to hrmpf on a USB drive?
Or maybe I should just do the minimum to get ssh going?

Cheers

**Comment by leahneukirchen** [comment]
There is `xchroot` which is close, https://github.com/leahneukirchen/xtools/blob/master/xchroot

**Comment by drudru** [comment]
Thank you :+1:
