### ISSUE TITLE
xbps-install doesn't use XBPS_ARCH env variable

### ISSUE THREAD

**Issue by mangoducksparkles** [leahneukirchen/hrmpf#20]
```
export XBPS_ARCH=x86_64-musl
xbps-install -S -R https://repo-us.voidlinux.org/current/musl
```
Works on the standard live image, but yields `ERROR: [reposync] failed to fetch file 'https://repo-us.voidlinux.org/current/musl/x86_64-repodata': Not Found` in hrmpf.

**Comment by leahneukirchen** [comment]
You can use `XBPS_TARGET_ARCH` instead, but not sure why hrmpf is different here.
