### ISSUE TITLE
ZFS thin-pool target support missing from kernel

### ISSUE THREAD

**Issue by leomania** [leahneukirchen/hrmpf#23]
Using hrmpf for the first time, experimenting with using it as a rescue distro with ZFS support. During boot on my Proxmox server I encountered this error:

```
=> Activating LVM devices...
  Can't process LV pve/data: thin-pool target support missing from kernel?
  2 logical volume(s) in volume group "pve" now active

Cannot continue due to errors above, starting emergency shell.
When ready type exit to continue booting.
/bin/sh: 0: can't access tty; job control turned off
# 
```

Cheers.

**Comment by leahneukirchen** [comment]
You should be able to boot by pressing `^C` here and later
```
modprobe dm-thin-pool
vgchange -a y
```

Does that work?

**Comment by leomania** [comment]
The commands do indeed work. I'm dropped to a root shell automatically, no need to hit ^C, so I just issued the commands. Here's what I see:

`# modprobe dm-thin-pool
# vgchange -a y
3 logical volume(s) in volume group "pve" now active
# `

So, looks good so far. Am I done at this point, or do I need to issue another command to have the boot process continue?

Thanks!

**Comment by leahneukirchen** [comment]
No, closing the shell with `exit` or `^C` should continue the boot.

**Comment by leomania** [comment]
That did the trick. Thanks!

Since this is a rescue distro it's not particularly important to make this work without intervention, but just for my own knowledge, is there a way to make this persistent, such as adding this as an entry in /etc/modules? I did try but the entry was gone next boot as expected.

Cheers!

**Comment by leahneukirchen** [comment]
You can add `rd.modules-load=dm-thin-pool` to the kernel command line I guess (in grub/syslinux config).
