### ISSUE TITLE
Booting into RAM (in Hyper-V) does fail without warning for insufficient memory

### ISSUE THREAD

**Issue by claudiusraphael** [leahneukirchen/hrmpf#24]
Wanted to play around with Void, Root-on-Zfs in a Hyper-V VM ...

I set initial RAM allocation in steps of 512MiB up until i landed at 3584MiB (3.5GiB) and even then it failed randomly with:

![image](https://user-images.githubusercontent.com/84972255/190892153-557ad28f-aca4-4127-94b2-d96e51b9c428.png)

A pre-allocation of 3840MiB guarantees a successful boot into RAM.

This may or may not be related to "hrmpf" - my only guess here would be that it tries to reserve an abnormous amount of RAM to copy (maybe extract as well temporarily) the squashed.img or that other roadblocks are involved for example lock/allocation of /tmp or zram - but as i said this is just a blind guess.

In any case, no matter if it is an issue with hrmpf or void itself - i also failed to find any verbose info regarding minimum RAM size for boot-to-ram in the documentation.

Since hrmpf is pointed towards to from the [void guide for ZFS setup](https://docs.voidlinux.org/installation/guides/zfs.html) directly:
![image](https://user-images.githubusercontent.com/84972255/190893072-b880fc21-427b-468a-9dba-4564d9312961.png)

as well as in [Void Linux Single Disk UEFI for zfsbootmenu](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI)
![image](https://user-images.githubusercontent.com/84972255/190893334-2ec053ae-7883-4b61-a2b7-2963954ce149.png)

 i leave this note here.

It would be nice to have the restrictions straightforward mentioned (as in in-the-head/straight-on-frontpage):
- here in the README.MD as well as
- in the official documentation.

All in all 3.8GiB seems to be quite out-of-bound for void as well as any installer for a linux distro (asides Ubuntu 22.04 which actually does crash even then).

While i rarely look at github, if you like to have specific tests done somewhen in the future, please provide steps/resources and i will feedback based on it, when i happen to stumble over it again.

Thanks for taking the time.

_Additional info:_

- Booted in VM Gen2/UEFI ran via Hyper-V on Windows 11 Pro
- Passthrough SSHD instead of VHD (shouldn't matter as it is not used at that point)
- No SecureBoot / No TPM
- Tested with and without Dynamic Memory
- Out of curiosity did 3 tests with VirtualBox: similar behavior
- host is Intel i5-7500 Kabylake / 2x 8GB DDR4

**Comment by leahneukirchen** [comment]
hrmpf needs to copy the whole ISO into RAM (essentially), so it needs 1.3GB space in `/run`.
However, `/run` is by default a tmpfs limited to half of the RAM, so you need around 4GB to boot it successfully.

You can boot on 2GB by appending ` rd.break=pre-udev` and then running `mount -o remount,size=1500M /run` in the shell, exiting it, and then hrmpf should come up.

The silencing of this out of memory error is unfortunate, but inherent in dracut, so a bug should be filed there instead.
At least the status code of dd should be checked.

**Comment by claudiusraphael** [comment]
Thanks for the explanation. I will give it another try with the mentioned rd.break/mount-combo. When doing so and time allows it to prepare a full set of trial runs i file a bug against dracut.
