### ISSUE TITLE
Packages request

### ISSUE THREAD

**Issue by Ypnose** [leahneukirchen/hrmpf#25]
Hello Leah,

Could you please add `binfmt-support` and `qemu-user-static` packages in the list ?

Once again, congratulations for your work !

**Comment by Ypnose** [comment]
Thanks ! `hrmpf` is a vital tool in my daily workflow.

**Comment by CMB** [comment]
It also might be nice to have the full qemu.
I, at least, have been known to use it from live environments.
That would	 significantly bloat the size though, possibly for very little gain.

**Comment by leahneukirchen** [comment]
binfmt-support is in v20231102

Full QEMU is too big, perhaps someone splits the package at some point, as e.g. Arch does: https://archlinux.org/packages/extra/x86_64/qemu/
