### ISSUE TITLE
nvme drive not visible..

### ISSUE THREAD

**Issue by zen0bit** [leahneukirchen/hrmpf#28]
I am downloaded last iso and booted up on real hardware.
 Tried to install void but I dont see my nvme drive...

**Comment by zen0bit** [comment]
Didn't tried older ISO or other distro but Void official ISO working..

**Comment by leahneukirchen** [comment]
Is the device in `/dev/nvme*` or do you just not see it in the installer?

**Comment by zen0bit** [comment]
Not checked real /dev/nvme just in installer...

**Comment by leahneukirchen** [comment]
7abbf650
