### ISSUE TITLE
2023-1124 iso missing void-installer

### ISSUE THREAD

**Issue by truck** [leahneukirchen/hrmpf#34]
The void-installer script is missing from the latest iso image.

- it is still mentioned in the motd.
- I am using this under qemu, haven't yet updated my memsticks.

Short discussion on irc brought in some comments, and a potential patch;  discussion there  indicates the issue could come from a move of the script into build-86-images .  Abby from irc suggested a minimal patch:

```
diff --git a/mkhrmpf.sh b/mkhrmpf.sh
index 8773a04..8d70e2f 100755
--- a/mkhrmpf.sh
+++ b/mkhrmpf.sh
@@ -17,7 +17,8 @@ printf '%s\n' '-*' 'e*' 'Eauth.*' 'Eauthpriv.*' > hrmpf-include/var/log/socklog/
 mkdir -p hrmpf-include/etc/skel hrmpf-include/root
 touch hrmpf-include/etc/skel/.vimrc hrmpf-include/root/.vimrc
 
-./mklive.sh \
+./build-x86-images.sh \
+	-b base -- \
 	-T "hrmpf live/rescue system" \
 	-C "loglevel=6 printk.time=1 consoleblank=0 net.ifnames=0" \
 	-r https://repo-default.voidlinux.org/current \
```

but ALSO mentioned there may be some duplication in services/packaging.  (Thus why I'm not submitting it as an ACTUAL patch.  Also, not my work.)

- obviously void-installer isn't neccesary, it's just a nice convenience.  A quicker solution would be to remove the mention of void-installer in the motd (:

**Comment by leahneukirchen** [comment]
Good catch, this is obviously a bug.

**Comment by classabbyamp** [comment]
probably simpler at this point to just grab this block instead of moving `mkhrmpf` to running `build-x86-images`

https://github.com/leahneukirchen/hrmpf/blob/ca6351ad61b0ac96de9d7b3a95e18ba805494af2/build-x86-images.sh#L132-L141
